/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-06-10 17:23:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>Log-In</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/menu.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/login.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"wrap\">\n");
      out.write("\t\t<aside class=\"left\">\n");
      out.write("\t\t\t<h1 id=\"home\">\n");
      out.write("\t\t\t\t<a href=\"main.jsp\"><img src=\"static/home.png\"></a>\n");
      out.write("\t\t\t</h1>\n");
      out.write("\t\t\t<!-- 카테고리 -->\n");
      out.write("\t\t\t<section id=\"category\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li style=\"margin-bottom: 10px;\"><a href=\"main.jsp\">HOME</a></li>\n");
      out.write("\t\t\t\t\t<li style=\"margin-bottom: 10px;\"><a href=\"product.jsp?gdCode=1\">IPHONE</a></li>\n");
      out.write("\t\t\t\t\t<li style=\"margin-bottom: 10px;\"><a href=\"product.jsp?gdCode=2\">AIRPODS</a></li>\n");
      out.write("\t\t\t\t\t<li style=\"margin-bottom: 10px;\"><a href=\"product.jsp?gdCode=3\">SMART\n");
      out.write("\t\t\t\t\t\t\tTOK</a></li>\n");
      out.write("\t\t\t\t\t<li style=\"margin-bottom: 10px;\"><a href=\"product.jsp?gdCode=4\">KEYRING</a></li>\n");
      out.write("\t\t\t\t\t<li style=\"margin-bottom: 10px;\"><a href=\"review.jsp\">REVIEW</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t</aside>\n");
      out.write("\t\t<aside id=\"right\"></aside>\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<header>\n");
      out.write("\t\t\t\t<div id=\"user\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.jsp\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"joinform.jsp\">회원가입</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"cart.jsp\">장바구니</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"contents\">\n");
      out.write("\t\t\t\t<div class=\"titleArea\">\n");
      out.write("\t\t\t\t\t<h2>LOGIN</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<form id=\"loginform\" method=\"post\" action=\"login\">\n");
      out.write("\t\t\t\t\t<div id=\"logdiv\" style=\"text-align: center;\">\n");
      out.write("\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"holder\"> <input id=\"id\" name=\"userID\"\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"ID\">\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"holder\"> <input id=\"pw\" name=\"userPW\"\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"password\" class=\"form-control\" placeholder=\"PASSWORD\">\n");
      out.write("\t\t\t\t\t\t\t</label> <label class=\"btnholder\"> <input id=\"loginsub\"\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"submit\" value=\"로그인\">\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<footer>\n");
      out.write("\t\t\t\t<div id=\"insta\">\n");
      out.write("\t\t\t\t\t<div class=\"titleArea\">\n");
      out.write("\t\t\t\t\t\t<h2>INSTAGRAM</h2>\n");
      out.write("\t\t\t\t\t\t<p onclick=\"window.open('http://www.instagram.com/potato_yunn')\">@potato_yun</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"f_menu\">\n");
      out.write("\t\t\t\t\t<span>ABOUT&nbsp;&nbsp;</span> <span>GUIDE&nbsp;&nbsp;</span> <span>AGREEMENT&nbsp;&nbsp;</span>\n");
      out.write("\t\t\t\t\t<span>PRIVACY</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
